services:
  app:
    container_name: 'app'
    build:
      context: .
      dockerfile: Dockerfile.development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      - RAILS_ENV=development
    env_file:
      - .env
    volumes:
      - ".:/toy_robot"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: 'redis'
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  redis-data:
